// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdwqiprfribpkuhpzcuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kd3FpcHJmcmlicGt1aHB6Y3V2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNTc2MDIsImV4cCI6MjA1OTgzMzYwMn0.ekb91tgre_UExZQq9Dfl9HcygOB1mZywhJ4XKDX4LIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);